import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useData } from '../../app/data/DataProvider';
import { DataState, ErrorMessage, useOperation } from '../../components/DataState';
import { Button, Card, PageHeading } from '../../components/ui';
import { exportCsv, exportJson, parseImport, type DuplicateAction, type ImportPreview } from '../../domain/transfer/format';
import { database } from '../../services/database';

export function TransferPage(){
 const data=useData();const [format,setFormat]=useState<'json'|'csv'>('json'),[kind,setKind]=useState<'vocabulary'|'grammar'>('vocabulary');
 const [input,setInput]=useState(''),[preview,setPreview]=useState<ImportPreview|null>(null),[issues,setIssues]=useState<string[]>([]),[actions,setActions]=useState<DuplicateAction[]>([]),[targets,setTargets]=useState<(string|null)[]>([]),[message,setMessage]=useState('');const {busy,error,run}=useOperation();const lock=useRef(false);
 function reset(){setPreview(null);setIssues([]);setMessage('');}
 const duplicate=(i:number)=>!!preview&&(preview.matches[i].ids.length>0||preview.matches[i].earlier!==null);
 async function download(type:'json'|'csv') {const rows=await database.transfer.export();const blob=new Blob([type==='json'?exportJson(rows):exportCsv(rows)],{type:type==='json'?'application/json;charset=utf-8':'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`nihongo-content-${new Date().toISOString().slice(0,10)}.${type}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(`${rows.length} materi diekspor sebagai ${type.toUpperCase()}.`);}
 return <><PageHeading eyebrow="データ / IMPORT & EXPORT" title="Bawa materi belajarmu." description="Periksa konten sebelum impor. Progres belajar yang sudah tersimpan tetap dipertahankan."/><DataState><Card className="transfer-panel"><h2>Tambahkan materi belajarmu</h2><p>Impor JSON/CSV untuk banyak materi sekaligus. Untuk beberapa kata atau pola, gunakan tambah manual.</p><div className="entry-actions"><Link className="button button-secondary" to="/vocabulary?add=1">Tambah vocabulary</Link><Link className="button button-secondary" to="/grammar?add=1">Tambah grammar</Link></div></Card>
 <Card className="transfer-panel"><h2>Import konten</h2><p>Mulai dengan contoh berkas, lalu ganti isinya dengan materi yang ingin dipelajari.</p><div className="entry-actions">{(['vocabulary','grammar'] as const).map(type => <span key={type}>{type === 'vocabulary' ? 'Vocabulary' : 'Grammar'}: <a className="text-link" href={'/templates/'+type+'.json'} download>Contoh JSON</a> · <a className="text-link" href={'/templates/'+type+'.csv'} download>Contoh CSV</a></span>)}</div><p>Merge mempertahankan ID dan progres. Kolom wajib mengikuti berkas; kolom tambahan yang kosong mempertahankan nilai lama. Kategori dan contoh digabung tanpa menggandakan yang sama. Keep Both membuat ID baru tanpa menyalin progres.</p><fieldset disabled={busy} className="data-form"><div className="form-columns"><label>Format impor<select aria-label="Format impor" value={format} onChange={e=>{reset();setFormat(e.target.value as 'json'|'csv');}}><option value="json">JSON</option><option value="csv">CSV</option></select></label><label>Jenis jika kolom type tidak ada<select aria-label="Jenis impor" value={kind} onChange={e=>{reset();setKind(e.target.value as typeof kind);}}><option value="vocabulary">Vocabulary</option><option value="grammar">Grammar</option></select></label></div>
 <label>Pilih berkas<input aria-label="Berkas impor" type="file" accept=".json,.csv,application/json,text/csv" onChange={e=>{const file=e.target.files?.[0];if(!file)return;reset();void run(async()=>{if(file.size>10*1024*1024)throw new Error('Batas berkas 10 MB.');const ext=file.name.toLowerCase().split('.').pop();if(ext!=='json'&&ext!=='csv')throw new Error('Pilih berkas .json atau .csv.');setFormat(ext);setInput(await file.text());});}}/></label>
 <label>Isi JSON / CSV<textarea aria-label="Isi impor" rows={10} value={input} onChange={e=>{reset();setInput(e.target.value);}} spellCheck={false}/></label>
 <Button disabled={busy||!input.trim()} onClick={()=>void run(async()=>{reset();const parsed=parseImport(input,format,kind);const errors=parsed.filter(r=>r.error).map(r=>`Item ${r.line}: ${r.error}`);setIssues(errors);if(errors.length)return;const next=await database.transfer.preview(parsed.flatMap(r=>r.row?[r.row]:[]));setPreview(next);setActions(next.rows.map(()=> 'ignore'));setTargets(next.matches.map(m=>m.ids.length===1?m.ids[0]:null));})}>Periksa impor</Button></fieldset>
 <details><summary>Format dan contoh</summary><p>Vocabulary wajib: kanji, kana, meaning, level. Grammar wajib: grammar (nama pola), meaning, pattern (struktur), level. Level: N5–N2. category, example, translation opsional. Kategori CSV dipisahkan titik koma; gunakan kutip untuk teks dengan koma atau baris baru. Maksimal 10 MB / 5000 item.</p><pre>{format==='csv'?(kind==='vocabulary'?'kanji,kana,meaning,level,category,example,translation\n改善,かいぜん,perbaikan,N3,仕事,仕事を改善する。,Memperbaiki pekerjaan.':'grammar,meaning,pattern,example,translation,level\n〜ながら,sambil,Vます tanpa ます + ながら,音楽を聞きながら勉強する。,Belajar sambil mendengarkan musik.,N3'):JSON.stringify(kind==='vocabulary'?[{kanji:'改善',kana:'かいぜん',meaning:'perbaikan',level:'N3',category:'仕事',example:'仕事を改善する。',translation:'Memperbaiki pekerjaan.'}]:[{grammar:'〜ながら',meaning:'sambil',pattern:'Vます tanpa ます + ながら',example:'音楽を聞きながら勉強する。',translation:'Belajar sambil mendengarkan musik.',level:'N3'}],null,2)}</pre></details>
 {issues.length>0&&<div role="alert"><h3>{issues.length} item perlu diperbaiki</h3><ul>{issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul><p>Belum ada data disimpan. Perbaiki isi berkas dan periksa lagi.</p></div>}
 </Card>
 {preview&&<Card className="transfer-panel"><h2>Pratinjau impor</h2><p>{preview.rows.length} item valid · {preview.matches.filter((_,i)=>duplicate(i)).length} duplikat terdeteksi.</p><label>Atur semua duplikat<select aria-label="Atur semua duplikat" disabled={busy} value="" onChange={e=>{setActions(actions.map(()=>e.target.value as DuplicateAction));}}><option value="" disabled>Pilih kebijakan</option><option value="merge">Merge</option><option value="keep-both">Keep Both</option><option value="ignore">Ignore</option></select></label>
 <p className="small-note">Duplikat: ID ekspor yang sama, atau kanji + kana / nama grammar yang sama setelah normalisasi. Jika beberapa materi cocok, pilih tujuan Merge. Untuk duplikat berkas tanpa kecocokan awal di database, Merge menggunakan hasil item pertama yang cocok. Isi lengkap tiap item dapat diperiksa di bawah.</p>
 <ol className="transfer-preview">{preview.rows.map((row,i)=><li key={i}><strong>{row.kanji??row.grammar} · {row.level}</strong><p>{row.meaning}</p>{duplicate(i)?<><p className="small-note">Duplikat {preview.matches[i].ids.length?'database':`item ${preview.matches[i].earlier!+1} dalam berkas`}</p><select aria-label={`Tindakan item ${i+1}`} disabled={busy} value={actions[i]} onChange={e=>setActions(actions.map((a,j)=>j===i?e.target.value as DuplicateAction:a))}><option value="merge">Merge</option><option value="keep-both">Keep Both</option><option value="ignore">Ignore</option></select>{preview.matches[i].ids.length>0&&<label>Tujuan Merge<select aria-label={`Tujuan item ${i+1}`} disabled={busy||actions[i]!=='merge'} value={targets[i]??''} onChange={e=>setTargets(targets.map((t,j)=>j===i?e.target.value:t))}><option value="">Pilih materi lama</option>{preview.matches[i].ids.map(id=>{const item=data[row.type].find(r=>r.id===id);return <option key={id} value={id}>{item?('kanji'in item?item.kanji:item.pattern):id} · {item?.meaning} · {id}</option>;})}</select></label>}</>:<p className="small-note">Materi baru</p>}<details><summary>Isi lengkap item {i+1}</summary><pre>{JSON.stringify(row,null,2)}</pre></details></li>)}</ol>
 <Button disabled={busy||preview.matches.some((m,i)=>m.ids.length>1&&actions[i]==='merge'&&!targets[i])} onClick={()=>{if(lock.current)return;lock.current=true;void run(async()=>{let result:{created:number;merged:number;ignored:number}|undefined;await data.mutate(async()=>{result=await database.transfer.commit(preview,actions,targets);});setMessage(`Impor selesai: ${result!.created} baru, ${result!.merged} digabung, ${result!.ignored} diabaikan. Progres lama tetap tersimpan.`);setPreview(null);}).finally(()=>{lock.current=false;});}}>{busy?'Menyimpan…':'Simpan impor'}</Button></Card>}
 <Card className="transfer-panel"><h2>Export konten</h2><p>Vocabulary, grammar, kategori, dan contoh kalimat. Progres, riwayat quiz, serta favorit tidak disertakan. Ini bukan backup seluruh aplikasi.</p><div className="entry-actions"><Button disabled={busy} onClick={()=>void run(()=>download('json'))}>Export JSON</Button><Button disabled={busy} variant="secondary" onClick={()=>void run(()=>download('csv'))}>Export CSV</Button></div></Card>
 <ErrorMessage message={error}/>{message&&<p className="info-banner" role="status">{message}</p>}</DataState></>;
}
