import { test, expect, type Page } from '@playwright/test';
import type { LearningDatabase } from '../src/repositories/contracts';
test.setTimeout(100_000);
// A minimal three-page PDF fixture with real xref offsets, rendered by PDF.js.
function pdfFixture(label = 'Nihongo Study') {
 const objects = ['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R 5 0 R 7 0 R] /Count 3 >>'];
 for(let i=0;i<3;i++){const text=`BT /F1 24 Tf 48 720 Td (${label} - Page ${i+1}) Tj 0 -42 Td /F1 14 Tf (Read. Practice. Remember.) Tj ET`;objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 9 0 R >> >> /Contents ${4+i*2} 0 R >>`,`<< /Length ${text.length} >>\nstream\n${text}\nendstream`);}
 objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let text='%PDF-1.4\n';const offsets=[0];objects.forEach((obj,i)=>{offsets.push(Buffer.byteLength(text));text+=`${i+1} 0 obj\n${obj}\nendobj\n`;});const xref=Buffer.byteLength(text);text+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>`${String(n).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(text);
}
async function ready(page: Page){await page.goto('/materials');await expect(page.getByText('Rak bukumu masih kosong.',{exact:true})).toBeVisible();}
async function upload(page: Page,name='Buku N3'){await page.getByRole('button',{name:'Add PDF',exact:true}).click();await page.getByLabel('Berkas PDF',{exact:true}).setInputFiles({name:'nihongo.pdf',mimeType:'application/pdf',buffer:pdfFixture()});await page.getByLabel('Nama PDF',{exact:true}).fill(name);await page.getByLabel('Sumber PDF',{exact:true}).fill('Koleksi pribadi Jepang');await page.getByRole('button',{name:'Simpan PDF',exact:true}).click();await expect(page.getByRole('dialog')).toBeHidden({timeout:45_000});}
async function pdfReady(page:Page){await expect(page.getByRole('button',{name:'Bookmark halaman',exact:true}).or(page.getByRole('button',{name:'Hapus bookmark',exact:true}))).toBeEnabled({timeout:30_000});}

test('upload, search, reader controls, completion and bookmarks persist without generating learning material',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);await upload(page);await expect(page.locator('.pdf-card')).toContainText('3 halaman');await page.getByLabel('Search PDF').fill('pribadi Jepang');await expect(page.locator('.pdf-card')).toHaveCount(1);await page.getByLabel('Search PDF').fill('tidak ada');await expect(page.locator('.pdf-card')).toHaveCount(0);await page.getByLabel('Search PDF').fill('nihongo');await page.getByRole('link',{name:'Open PDF'}).click();await pdfReady(page);await expect(page.getByRole('button',{name:'Previous page',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Next page',exact:true}).click();await pdfReady(page);await expect(page.getByLabel('Page number')).toHaveValue('2');await page.getByRole('button',{name:'Bookmark halaman',exact:true}).click();await expect(page.getByRole('button',{name:'Hapus bookmark',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Tandai halaman selesai',exact:true}).click();await expect(page.getByRole('progressbar',{name:'Progres membaca PDF'})).toHaveAttribute('aria-valuenow','1');await page.reload();await pdfReady(page);await expect(page.getByRole('button',{name:'Batalkan halaman selesai',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByLabel('Zoom',{exact:true}).selectOption('2');await pdfReady(page);await page.getByLabel('Page number').fill('3');await page.getByRole('button',{name:'Buka',exact:true}).click();await pdfReady(page);await expect(page.getByRole('button',{name:'Next page',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Halaman 2',exact:true}).click();await pdfReady(page);
 const state=await page.evaluate(async()=>{const u='/src/services/database.ts';const db=(await import(u)).database as LearningDatabase;const m=(await db.materials.list()).find(m=>m.file)!;return {m,size:(await db.pdf.getFile(m.file!))?.size,p:await db.progress.list(),v:(await db.vocabulary.list()).length,g:(await db.grammar.list()).length,s:await db.sessions.list(),r:await db.pdf.reading(m.id)};});expect(state.size).toBeGreaterThan(0);expect(state.p).toHaveLength(0);expect(state.s).toHaveLength(0);expect(state.v).toBe(70);expect(state.g).toBe(30);expect(state.m.completedPages).toBe(1);expect(state.r?.completedPageNumbers).toEqual([2]);
 await page.goto('/favorites');await page.getByRole('link',{name:'Buka halaman PDF'}).click();await pdfReady(page);await expect(page.getByLabel('Page number')).toHaveValue('2');await page.getByRole('button',{name:'Batalkan halaman selesai',exact:true}).click();await expect(page.getByRole('progressbar',{name:'Progres membaca PDF'})).toHaveAttribute('aria-valuenow','0');await page.getByRole('button',{name:'Hapus bookmark',exact:true}).click();await expect(page.getByRole('button',{name:'Bookmark halaman',exact:true})).toBeVisible();expect(errors).toEqual([]);
});

test('rejects invalid, damaged and duplicate PDFs atomically; deleting removes file, tracking and bookmarks',async({page})=>{
 await ready(page);await upload(page);await page.getByRole('button',{name:'Add PDF',exact:true}).click();const input=page.getByLabel('Berkas PDF',{exact:true});await input.setInputFiles({name:'fake.pdf',mimeType:'application/pdf',buffer:Buffer.from('not pdf')});await page.getByRole('button',{name:'Simpan PDF',exact:true}).click();await expect(page.getByText('Berkas ini bukan PDF yang valid.',{exact:true})).toBeVisible();await input.setInputFiles({name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n corrupt')});await page.getByRole('button',{name:'Simpan PDF',exact:true}).click();await expect(page.locator('.form-error')).toBeVisible();await input.setInputFiles({name:'duplicate.pdf',mimeType:'application/pdf',buffer:pdfFixture()});await page.getByRole('button',{name:'Simpan PDF',exact:true}).click();await expect(page.locator('.form-error')).toContainText('sudah ada');await page.getByRole('button',{name:'Batal',exact:true}).click();await expect(page.locator('.pdf-card')).toHaveCount(1);
 const id=await page.evaluate(async()=>{const u='/src/services/database.ts';const db=(await import(u)).database as LearningDatabase;const m=(await db.materials.list()).find(m=>m.file)!;await db.pdf.complete(m.id,2,true);await db.pdf.bookmark(m.id,2,true);return m.id;});await page.reload();await page.getByRole('button',{name:'Delete PDF Buku N3',exact:true}).click();await page.getByRole('button',{name:'Hapus PDF',exact:true}).click();await expect(page.locator('.pdf-card')).toHaveCount(0);await page.reload();await expect(page.getByText('Rak bukumu masih kosong.',{exact:true})).toBeVisible();const cleared=await page.evaluate(async(id)=>{const u='/src/services/database.ts';const db=(await import(u)).database as LearningDatabase;return {m:await db.materials.get(id),f:!!await db.pdf.getFile(id),r:await db.pdf.reading(id),favorites:await db.favorites.list()};},id);expect(cleared).toEqual({m:undefined,f:false,r:undefined,favorites:[]});await page.goto(`/materials/${id}`);await expect(page.getByRole('heading',{name:'PDF tidak tersedia',exact:true})).toBeVisible();
});

test('source references validate pages, open correct page and prevent deletion of referenced PDF',async({page})=>{
 await ready(page);await upload(page);const saved=await page.evaluate(async()=>{const u='/src/services/database.ts';const db=(await import(u)).database as LearningDatabase;const m=(await db.materials.list()).find(m=>m.file)!;const v=(await db.vocabulary.list())[0];await db.vocabulary.update(v.id,{sourcePdfId:m.id,sourcePage:2});let invalid=false,blocked=false;try{await db.vocabulary.update(v.id,{sourcePage:4});}catch{invalid=true;}try{await db.pdf.delete(m.id);}catch{blocked=true;}await Promise.all([db.pdf.complete(m.id,1,true),db.pdf.complete(m.id,2,true),db.pdf.complete(m.id,1,true)]);return {v:v.id,id:m.id,invalid,blocked,pages:(await db.materials.get(m.id))?.completedPages};});expect(saved.invalid).toBe(true);expect(saved.blocked).toBe(true);expect(saved.pages).toBe(2);await page.goto(`/vocabulary/${saved.v}`);await page.getByRole('link',{name:'Buka halaman sumber'}).click();await pdfReady(page);await expect(page.getByLabel('Page number')).toHaveValue('2');await expect(page.getByRole('progressbar',{name:'Progres membaca PDF'})).toHaveAttribute('aria-valuenow','2');
});

test('reader fits mobile, zoom stays inside viewer, resume and missing/dummy routes work',async({page})=>{
 await ready(page);await upload(page);await page.getByRole('link',{name:'Open PDF'}).click();await pdfReady(page);await page.getByRole('button',{name:'Next page',exact:true}).click();await pdfReady(page);await page.getByRole('link',{name:'Kembali ke materi PDF',exact:true}).click();await page.getByRole('link',{name:'Open PDF'}).click();await pdfReady(page);await expect(page.getByLabel('Page number')).toHaveValue('2');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await pdfReady(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.screenshot({path:'test-results/pdf-reader-desktop.png',fullPage:true});await page.setViewportSize({width:320,height:900});await page.getByLabel('Zoom',{exact:true}).selectOption('3');await pdfReady(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByLabel('Zoom',{exact:true}).selectOption('1');await pdfReady(page);await page.screenshot({path:'test-results/pdf-reader-mobile.png',fullPage:true});await page.getByRole('button',{name:'Aktifkan mode gelap'}).click();await page.screenshot({path:'test-results/pdf-reader-dark.png',fullPage:true});await page.goto('/materials/seed-N3-vocabulary?page=999');await expect(page.getByRole('heading',{name:'Referensi dummy tanpa berkas'})).toBeVisible();
});

test('version 4 migration preserves legacy sourcePdf aliases and history with canonical sourcePdfId',async({page})=>{
 await page.addInitScript(()=>{if(sessionStorage.getItem('pdf-migration'))return;sessionStorage.setItem('pdf-migration','1');const r=indexedDB.open('nihongo-master',4);r.onupgradeneeded=()=>{for(const name of ['vocabulary','grammar','examples','categories','materials','pages','questions','progress','favorites','schedules','quizResults','quizAttempts','reviewRuns','sessions','reviewEvents','meta'])r.result.createObjectStore(name,{keyPath:'id'});const tx=r.transaction!;const stamp=new Date().toISOString();tx.objectStore('meta').put({id:'seed-v1',value:stamp});tx.objectStore('materials').put({id:'legacy',title:'Legacy source',filename:'legacy.pdf',pageCount:3,isDummy:true,status:'REFERENCE_ONLY',checksum:null,createdAt:stamp,updatedAt:stamp});tx.objectStore('vocabulary').put({id:'kept',sourcePdf:'legacy',sourcePage:2,additionalSources:[{sourcePdf:'legacy',sourcePage:1}],kanji:'保存',kana:'ほぞん',meaning:'Simpan',categoryIds:[],jlptLevel:'N3',createdAt:stamp,updatedAt:stamp});tx.objectStore('quizResults').put({id:'history',finishedAt:stamp,score:100,accuracy:100,answers:[{questionSnapshot:{sourcePdf:'legacy',sourcePage:3,itemType:'vocabulary',itemId:'kept',jlptLevel:'N3'},isCorrect:true}]});};r.onsuccess=()=>r.result.close();});
 await page.goto('/materials');await expect(page.getByText('Rak bukumu masih kosong.',{exact:true})).toBeVisible();const saved=await page.evaluate(async()=>{const u='/src/services/database.ts';const db=(await import(u)).database as LearningDatabase;return {m:await db.materials.get('legacy'),v:await db.vocabulary.get('kept'),q:await db.quizResults.get('history')};});expect(saved.v?.sourcePdfId).toBe('legacy');expect(saved.v?.additionalSources[0].sourcePdfId).toBe('legacy');expect(saved.q?.answers[0].questionSnapshot.sourcePdfId).toBe('legacy');expect(saved.m).toMatchObject({name:'Legacy source',totalPages:3,completedPages:0,file:null});await page.reload();await expect(page.getByText('Rak bukumu masih kosong.',{exact:true})).toBeVisible();
});

test('size and storage quota failures leave no partial material',async({page})=>{
 await ready(page);const result=await page.evaluate(async(bytes)=>{const u='/src/services/database.ts';const db=(await import(u)).database as LearningDatabase;const normal=new File([new Uint8Array(bytes)],'test.pdf',{type:'application/pdf'});let size='',quota='';try{await db.pdf.upload(new File([new ArrayBuffer(51*1024*1024)],'large.pdf',{type:'application/pdf'}),'Large','');}catch(e){size=String(e);}const original=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(value,key){if(this.name==='pdfFiles')throw new DOMException('Full','QuotaExceededError');return original.call(this,value,key);};try{await db.pdf.upload(normal,'Quota','');}catch(e){quota=String(e);}finally{IDBObjectStore.prototype.add=original;}return {size,quota,files:(await db.materials.list()).filter(m=>m.file).length};},[...pdfFixture('Quota')]);expect(result.size).toContain('50 MB');expect(result.quota).toContain('penuh');expect(result.files).toBe(0);await page.reload();await expect(page.locator('.pdf-card')).toHaveCount(0);
});

test('Japanese PDF renders with local resources and remains readable without external network after reload',async({page,context})=>{
 const fixture=await context.newPage();await fixture.setContent('<html lang="ja"><meta charset="utf-8"><style>body{font-family:sans-serif;padding:40px}h1{font-size:36px}p{font-size:24px}</style><h1>日本語の学習</h1><p>毎日少しずつ勉強します。</p><p>語彙と文法を復習しましょう。</p></html>');const buffer=await fixture.pdf({format:'A4'});await fixture.close();await ready(page);await page.getByRole('button',{name:'Add PDF',exact:true}).click();await page.getByLabel('Berkas PDF',{exact:true}).setInputFiles({name:'japanese.pdf',mimeType:'application/pdf',buffer});await page.getByRole('button',{name:'Simpan PDF',exact:true}).click();await expect(page.getByRole('dialog')).toBeHidden({timeout:45_000});await page.getByRole('link',{name:'Open PDF'}).click();await pdfReady(page);await page.screenshot({path:'test-results/pdf-reader-japanese.png',fullPage:true});
 // App hosting remains available; reject all external network to verify no CDN dependency.
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());await page.reload();await pdfReady(page);await expect(page.getByRole('img',{name:'PDF halaman 1'})).toBeVisible();
});
