import { Card, ProgressBar } from '../../components/ui';
import { duration, percent, statuses, statusLabels, type ProgressAnalytics } from '../../domain/analytics/progress';

export function LevelProgress({ levels }: { levels: ProgressAnalytics['levels'] }) {
  return <div className="study-grid">{levels.map(row => <Card className="progress-level" key={row.level}><h2>JLPT {row.level}</h2>{([
    ['Vocabulary', row.vocabulary.coverage], ['Grammar', row.grammar.coverage], ['Quiz', row.quiz], ['Overall', row.overall],
  ] as const).map(([label, value]) => <div className="progress-line" key={label}><div><span>{label}</span><strong>{percent(value)}</strong></div><ProgressBar value={value ?? 0} label={`${row.level} ${label}`} /></div>)}<p className="small-note">{row.vocabulary.assessed}/{row.vocabulary.total} kata · {row.grammar.assessed}/{row.grammar.total} pola diuji · {row.questions} jawaban quiz</p></Card>)}</div>;
}
export function MasteryChart({ title, data }: { title: string; data: ProgressAnalytics['vocabulary'] }) {
  return <Card className="analytics-panel"><h2>{title} mastery</h2><p className="muted">Distribusi status dari {data.total} materi saat ini.</p><div className="mastery-stack" aria-hidden="true">{statuses.map(s => data.counts[s] > 0 && <span key={s} className={`mastery-${s.toLowerCase()}`} style={{ flex: data.counts[s] }} />)}</div><ul className="mastery-legend">{statuses.map(s => <li key={s}><span><i className={`mastery-${s.toLowerCase()}`} />{statusLabels[s]}</span><strong>{data.counts[s]}</strong></li>)}</ul>{data.total === 0 && <p className="small-note">Belum ada materi tersimpan.</p>}</Card>;
}
export function QuizChart({ quizzes }: { quizzes: ProgressAnalytics['quizzes'] }) {
  const recent = quizzes.slice(-30);
  const x = (i: number) => recent.length === 1 ? 320 : 45 + i * 550 / (recent.length - 1);
  return <Card className="analytics-panel"><h2>Quiz score over time</h2><p className="muted">Maksimal 30 quiz terakhir, berurutan sesuai waktu selesai.</p>{recent.length ? <><svg className="score-chart" viewBox="0 0 640 240" role="img" aria-label="Grafik skor quiz, skala 0 sampai 100 persen. Rincian tersedia di bawah.">{[0, 50, 100].map(n => <g key={n}><line x1="45" x2="595" y1={205 - n * 1.7} y2={205 - n * 1.7} className="chart-grid" /><text x="5" y={210 - n * 1.7}>{n}%</text></g>)}<polyline points={recent.map((q, i) => `${x(i)},${205 - q.score * 1.7}`).join(' ')} fill="none" className="chart-line" />{recent.map((q, i) => <circle key={q.id} cx={x(i)} cy={205 - q.score * 1.7} r="4" className="chart-dot"><title>{new Date(q.finishedAt).toLocaleString('id-ID')}: {percent(q.score)}</title></circle>)}</svg><div className="chart-dates"><span>{new Date(recent[0].finishedAt).toLocaleDateString('id-ID')}</span><span>{new Date(recent[recent.length - 1].finishedAt).toLocaleDateString('id-ID')}</span></div><details><summary>Rincian skor quiz</summary><div className="analytics-table-wrap"><table><thead><tr><th>Selesai</th><th>Skor</th><th>Akurasi</th></tr></thead><tbody>{recent.map(q => <tr key={q.id}><td>{new Date(q.finishedAt).toLocaleString('id-ID')}</td><td>{percent(q.score)}</td><td>{percent(q.accuracy)}</td></tr>)}</tbody></table></div></details></> : <div className="chart-empty">Belum ada quiz selesai. Skor akan muncul setelah kamu menyelesaikan quiz.</div>}</Card>;
}
export function ActivityChart({ activity }: { activity: ProgressAnalytics['study']['activity'] }) {
  const max = Math.max(1, ...activity.map(d => d.sessions));
  return <Card className="analytics-panel"><h2>Study activity</h2><p className="muted">Jumlah sesi belajar per hari · 30 hari terakhir.</p><div className="activity-bars" role="img" aria-label="Grafik aktivitas belajar 30 hari. Rincian tanggal, sesi dan durasi tersedia di bawah.">{activity.map(d => <div key={d.date} title={`${d.date}: ${d.sessions} sesi, ${duration(d.seconds)}`}><span style={{ height: `${d.sessions / max * 100}%` }} /></div>)}</div><div className="chart-dates"><span>{activity[0].date}</span><span>{activity[29].date}</span></div><details><summary>Rincian aktivitas harian</summary><div className="analytics-table-wrap"><table><thead><tr><th>Tanggal</th><th>Sesi</th><th>Waktu aktif</th></tr></thead><tbody>{activity.map(d => <tr key={d.date}><td>{d.date}</td><td>{d.sessions}</td><td>{duration(d.seconds)}</td></tr>)}</tbody></table></div></details></Card>;
}
