import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useData } from '../../app/data/DataProvider';
import { calculateDashboard } from '../../domain/analytics/dashboard';
import { percent } from '../../domain/analytics/progress';
import { Badge, Button, Card, SectionHeading } from '../../components/ui';
import { ErrorMessage, useOperation } from '../../components/DataState';
import { database } from '../../services/database';

export function SmartDashboard() {
 const data=useData(), navigate=useNavigate(); const [now,setNow]=useState(()=>new Date());const {busy,error,run}=useOperation();
 useEffect(()=>{const update=()=>setNow(new Date());const timer=setInterval(update,10_000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update);};},[]);
 const smart=useMemo(()=>calculateDashboard(data,now),[data,now]);
 const recommendation=smart.recommendation, isDue=recommendation && smart.due.some(row=>row.progress.id===recommendation.progress.id);
 const url=(kind:string,id:string)=>`/${kind}/${encodeURIComponent(id)}`;
 return <section className="smart-dashboard" aria-label="Rekomendasi belajar">
  <Card className="smart-recommendation" data-testid="recommendation"><Badge>RECOMMENDED / おすすめ</Badge>
   {recommendation ? <><h2>{isDue?'Saatnya mengulang.':'Perkuat pemahamanmu.'}</h2><p>{recommendation.progress.itemType==='grammar'?'Grammar':'Vocabulary'} <strong lang="ja">{recommendation.title}</strong>{recommendation.progress.masteryScore===null?' belum memiliki nilai mastery.':` memiliki mastery ${percent(recommendation.progress.masteryScore)}.`} {isDue?'Direkomendasikan untuk review karena jadwalnya sudah jatuh tempo.':'Masih perlu penguatan; buka materi untuk membaca penjelasannya.'}</p><p className="small-note">{recommendation.progress.wrongCount} salah · {recommendation.progress.correctCount} benar · {recommendation.progress.reviewCount} review{!isDue&&recommendation.nextReview?` · Review berikutnya ${new Date(recommendation.nextReview).toLocaleString('id-ID')}`:''}</p><Link className="button button-primary" to={url(recommendation.progress.itemType,recommendation.item.id)}>{isDue?'Review Material':'Buka materi'}</Link>{isDue&&<Link className="text-link" to={`/review?type=${recommendation.progress.itemType}`}>Buka antrean review</Link>}</> : <><h2>{smart.vocabulary.available+smart.grammar.available?'Mulai dari materi yang belum dipelajari.':'Semua jadwalmu sudah teratur.'}</h2><p>{smart.vocabulary.available+smart.grammar.available?'Belum ada materi lemah atau review jatuh tempo. Pilih saran belajar di bawah.':'Tidak ada rekomendasi penguatan saat ini. Kamu dapat melihat progres atau menambahkan materi.'}</p><Link className="text-link" to={data.vocabulary.length+data.grammar.length?'/progress':'/materials'}>{data.vocabulary.length+data.grammar.length?'Lihat progres':'Tambah materi'}</Link></>}
  </Card>
  <div className="smart-grid"><Card className="smart-panel" data-testid="daily-learning"><SectionHeading title="今日の学習" subtitle="Saran untuk sesi berikutnya" />
   <p className="small-note">Jumlah vocabulary dan grammar menyesuaikan materi yang belum dinilai. Jumlah soal mengikuti riwayat quiz dan ketersediaan soal. Ini saran, bukan target wajib.</p>
   {(['vocabulary','grammar'] as const).map(kind=><div className="smart-learning-row" key={kind}><strong>{smart[kind].items.length} {kind==='vocabulary'?'Vocabulary':'Grammar'}</strong><span className="small-note">{smart[kind].available} materi belum dinilai</span>{smart[kind].items.length>0?<details><summary>Lihat saran {kind}</summary><ul className="smart-material-list">{smart[kind].items.map(item=><li key={item.id}><Link to={url(kind,item.id)} lang="ja">{'kanji'in item?item.kanji:item.pattern}</Link><span>{item.meaning}</span></li>)}</ul></details>:<p className="small-note">Tidak ada materi baru untuk disarankan.</p>}</div>)}
   <div className="smart-learning-row"><strong>{smart.quiz?.config.count??0} Soal quiz</strong>{smart.quiz?<><p className="small-note">{smart.quiz.config.mode} · {smart.quiz.available} soal dapat dipilih sesuai mode.</p><Button disabled={busy} onClick={()=>void run(async()=>{const attempt=await database.quiz.start(smart.quiz!.config);navigate(`/quiz?attempt=${attempt.id}`);})}>{busy?'Menyiapkan…':'Mulai quiz rekomendasi'}</Button></>:<p className="small-note">Materi belum cukup untuk sesi quiz. Tambahkan atau setujui materi terlebih dahulu.</p>}</div><ErrorMessage message={error}/>
  </Card>
  <Card className="smart-panel" data-testid="daily-review"><SectionHeading title="今日の復習" subtitle="Jatuh tempo sekarang, termasuk yang terlambat" />{(['vocabulary','grammar'] as const).map(kind=><div className="smart-learning-row" key={kind}><strong>{smart.due.filter(row=>row.progress.itemType===kind).length} {kind==='vocabulary'?'Vocabulary':'Grammar'}</strong>{smart.due.some(row=>row.progress.itemType===kind)&&<Link className="text-link" to={`/review?type=${kind}`}>Review {kind}</Link>}</div>)}{smart.due.length?<Link className="button button-secondary" to="/review?type=mixed">Buka semua review ({smart.due.length})</Link>:<p className="small-note">Tidak ada review jatuh tempo. Jadwal mendatang belum dimasukkan.</p>}<h3>Sudah dipelajari hari ini</h3><p className="small-note" data-testid="today-learned">{smart.today.vocabulary} vocabulary · {smart.today.grammar} grammar · {smart.today.quiz} jawaban dalam {smart.today.quizzes} quiz selesai.</p><p className="small-note">Vocabulary dan grammar dihitung sebagai materi unik yang dinilai hari ini; satu materi dapat juga muncul dalam quiz.</p></Card></div>
  <Card className="smart-panel" data-testid="weak-materials"><SectionHeading title={`⚠️ Weak Materials (${smart.weak.length})`} subtitle="Status Weak atau mastery di bawah 60% setelah latihan"/>{smart.weak.length?<ul className="smart-weak-list">{smart.weak.slice(0,6).map(row=><li key={row.progress.id}><Link to={url(row.progress.itemType,row.item.id)} lang="ja">{row.title}</Link><span>{row.progress.itemType} · Mastery {percent(row.progress.masteryScore)}</span><span className="small-note">{row.progress.wrongCount} salah · {row.progress.correctCount} benar</span></li>)}</ul>:<p className="muted">Belum ada materi lemah yang teridentifikasi. Materi yang belum dinilai tidak dianggap lemah.</p>}{smart.weak.length>6&&<details><summary>Lihat materi lemah lainnya ({smart.weak.length-6})</summary><ul className="smart-material-list">{smart.weak.slice(6).map(row=><li key={row.progress.id}><Link to={url(row.progress.itemType,row.item.id)}>{row.title}</Link><span>Mastery {percent(row.progress.masteryScore)}</span></li>)}</ul></details>}</Card>
 </section>;
}
