import { useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Files, Plus, BookOpen, Trash2, Search } from 'lucide-react';
import { useData } from '../../app/data/DataProvider';
import { DataState, ErrorMessage, useOperation } from '../../components/DataState';
import { Badge, Button, Card, EmptyState, PageHeading, ProgressBar } from '../../components/ui';
import { Modal } from '../../components/Modal';
import { database } from '../../services/database';
import type { PDFMaterial } from '../../domain/models';

export function MaterialsPage() {
  const data = useData(); const [query, setQuery] = useState(''); const [adding, setAdding] = useState(false); const [removing, setRemoving] = useState<PDFMaterial | null>(null);
  const { busy, error, run } = useOperation(); const uploadLock = useRef(false); const [uploadName, setUploadName] = useState('');
  const uploaded = data.materials.filter(m => !!m.file);
  const items = uploaded.filter(m => `${m.name} ${m.filename} ${m.source}`.normalize('NFKC').toLocaleLowerCase().includes(query.normalize('NFKC').trim().toLocaleLowerCase())).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  function upload(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (uploadLock.current) return; uploadLock.current = true;
    const form = new FormData(event.currentTarget);
    void run(() => data.mutate(() => database.pdf.upload(form.get('file') as File, String(form.get('name')), String(form.get('source')))), () => setAdding(false)).finally(() => { uploadLock.current = false; });
  }
  return <><PageHeading eyebrow="教材 / MATERI PDF" title="Semua bermula dari materimu." description="Simpan PDF, tandai halaman, dan lanjutkan bacaanmu kapan saja."><Button onClick={() => { setUploadName(''); setAdding(true); }}><Plus size={17} />Add PDF</Button></PageHeading><DataState><div className="pdf-summary"><Card><strong>{uploaded.length}</strong><span>PDF tersimpan</span></Card><Card><strong>{uploaded.reduce((n, m) => n + m.completedPages, 0)}</strong><span>Halaman selesai</span></Card><Card><strong>{uploaded.reduce((n, m) => n + m.totalPages, 0)}</strong><span>Total halaman</span></Card></div><label className="pdf-search"><Search size={18} /><input aria-label="Search PDF" placeholder="Cari judul, nama berkas, atau sumber…" value={query} onChange={e => setQuery(e.target.value)} /></label>
    {!adding && !removing && <ErrorMessage message={error} />}
    {items.length ? <div className="pdf-grid">{items.map(m => <Card className="pdf-card" key={m.id}><div className="pdf-card-top"><span className="icon-tile green"><Files size={22} /></span><Badge tone="neutral">PDF · {m.totalPages} halaman</Badge></div><h2>{m.name}</h2><p className="muted pdf-filename">{m.filename}</p><p className="pdf-source">Sumber: {m.source || 'Berkas pribadi'}</p><p className="small-note">Ditambahkan {new Date(m.createdAt).toLocaleDateString('id-ID')}</p><div className="progress-line"><div><span>{m.completedPages} / {m.totalPages} selesai</span><strong>{Math.round(m.completedPages / m.totalPages * 100)}%</strong></div><ProgressBar label={`Progres PDF ${m.name}`} value={m.completedPages} max={m.totalPages} /></div><div className="entry-actions"><Link className="button button-primary" to={`/materials/${encodeURIComponent(m.id)}`}><BookOpen size={16} />Open PDF</Link><Link className="button button-secondary" to={`/material-check?pdf=${m.id}`}>Extract / Material Review</Link><Button variant="secondary" onClick={() => setRemoving(m)} aria-label={`Delete PDF ${m.name}`}><Trash2 size={16} />Delete PDF</Button></div></Card>)}</div> : <EmptyState icon={Files} title={query ? 'PDF tidak ditemukan.' : 'Rak bukumu masih kosong.'} description={query ? 'Coba judul, nama berkas, atau sumber lain.' : 'Pilih Add PDF untuk mengunggah berkas pertamamu. Referensi seed tidak dihitung sebagai PDF unggahan.'} />}
    <p className="small-note">Berkas disimpan di browser ini. Menandai halaman selesai tidak menambah mastery vocabulary atau grammar. Hasil ekstraksi perlu diperiksa dan disetujui sebelum masuk database.</p>
  </DataState>
  {adding && <Modal title="Add PDF" busy={busy} onClose={() => setAdding(false)}><form className="data-form" onSubmit={upload}><fieldset disabled={busy}><label>Berkas PDF<input name="file" type="file" accept="application/pdf,.pdf" required onChange={e => { if (e.target.files?.[0]) setUploadName(e.target.files[0].name.replace(/\.pdf$/i, '')); }} /></label><p className="small-note">Maksimal 50 MB dan 5.000 halaman. PDF berkata sandi belum didukung.</p><label>Nama PDF<input name="name" required maxLength={200} value={uploadName} onChange={e => setUploadName(e.target.value)} /></label><label>Sumber PDF<input name="source" maxLength={2000} placeholder="Contoh: buku pribadi, penerbit, atau alamat sumber" /></label></fieldset><ErrorMessage message={error} /><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={() => setAdding(false)}>Batal</Button><Button type="submit" disabled={busy}>{busy ? 'Memeriksa dan menyimpan PDF…' : 'Simpan PDF'}</Button></div></form></Modal>}
  {removing && <Modal title="Hapus PDF?" busy={busy} onClose={() => setRemoving(null)}><p>Hapus “{removing.name}”, bookmark, dan progres halamannya dari browser ini? Berkas asli di perangkat tidak dihapus.</p><p className="small-note">PDF yang masih menjadi sumber materi harus dilepas dari referensi materi terlebih dahulu.</p><ErrorMessage message={error} /><div className="form-actions"><Button variant="secondary" disabled={busy} onClick={() => setRemoving(null)}>Batal</Button><Button disabled={busy} onClick={() => void run(() => data.mutate(() => database.pdf.delete(removing.id)), () => setRemoving(null))}>Hapus PDF</Button></div></Modal>}
  </>;
}
