import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { FileCheck2, ScanText } from 'lucide-react';
import { useData } from '../../app/data/DataProvider';
import { database } from '../../services/database';
import { extractMaterial } from '../../services/extraction';
import { missingFields } from '../../domain/extraction/identify';
import type { ContentKind, DraftEdit, DraftKind, ExtractionDraft, ExtractionFields, ExtractionRun, JLPTLevel, PDFPage } from '../../domain/models';
import { Badge, Button, Card, EmptyState, PageHeading, ProgressBar } from '../../components/ui';
import { DataState, ErrorMessage, useOperation } from '../../components/DataState';
import { Modal } from '../../components/Modal';
const labels:Record<keyof ExtractionFields,string>={kanji:'Kanji',kana:'Kana',meaning:'Meaning',pattern:'Grammar pattern',formation:'Pattern structure',explanation:'Explanation',example:'Example',translation:'Example translation',romaji:'Romaji',partOfSpeech:'Part of speech'};
const fieldsFor=(kind:DraftKind):(keyof ExtractionFields)[]=>kind==='vocabulary'?['kanji','kana','meaning','example','translation','romaji','partOfSpeech']:kind==='grammar'?['pattern','meaning','formation','explanation','example','translation']:['example','translation'];
export function MaterialCheckPage(){
 const data=useData();const [params,setParams]=useSearchParams();const materialId=params.get('pdf')??'';const selected=data.materials.find(m=>m.id===materialId&&m.file);
 const [runs,setRuns]=useState<ExtractionRun[]>([]),[drafts,setDrafts]=useState<ExtractionDraft[]>([]),[pages,setPages]=useState<PDFPage[]>([]),[loadError,setLoadError]=useState('');
 const [status,setStatus]=useState('PENDING'),[kind,setKind]=useState('all'),[pageNumber,setPageNumber]=useState('all'),[pageIndex,setPageIndex]=useState(0);
 const [editing,setEditing]=useState<ExtractionDraft|null>(null),[approving,setApproving]=useState<ExtractionDraft|null>(null),[removing,setRemoving]=useState<ExtractionDraft|null>(null);
 const operation=useOperation(),[extracting,setExtracting]=useState(false),[extractError,setExtractError]=useState('');const abort=useRef<AbortController|null>(null),mounted=useRef(true),generation=useRef(0);
 const refresh=useCallback(async()=>{const ticket=++generation.current;try {const [r,d,p]=await Promise.all([database.extraction.runs(),database.extraction.drafts(),database.pages.list()]);if(mounted.current&&ticket===generation.current){setRuns(r);setDrafts(d);setPages(p);setLoadError('');}}catch(e){if(mounted.current)setLoadError(e instanceof Error?e.message:'Gagal membaca draf.');}},[]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;abort.current?.abort();generation.current++;};},[]);
 useEffect(()=>{if(!data.loading&&!data.error)void refresh();},[data.loading,data.error,data.materials,refresh]);
 useEffect(()=>{const update=()=>void refresh();window.addEventListener('focus',update);let channel:BroadcastChannel|undefined;try{channel=new BroadcastChannel('nihongo-master:data');channel.onmessage=update;}catch{/* focus remains available */}return()=>{window.removeEventListener('focus',update);channel?.close();};},[refresh]);
 useEffect(()=>{setPageIndex(0);},[materialId,status,kind,pageNumber]);
 const run=runs.find(r=>r.materialId===materialId);const own=pages.filter(p=>p.materialId===materialId&&p.extractionStatus).sort((a,b)=>a.pageNumber-b.pageNumber);const relevant=drafts.filter(d=>d.sourcePdfId===materialId);const filtered=relevant.filter(d=>d.status===status&&(kind==='all'||d.kind===kind)&&(pageNumber==='all'||d.sourcePage===Number(pageNumber))).sort((a,b)=>a.sourcePage-b.sourcePage||a.id.localeCompare(b.id));
 const maxPage=Math.max(0,Math.ceil(filtered.length/12)-1),index=Math.min(pageIndex,maxPage);
 async function extract(){if(!selected||abort.current)return;const controller=new AbortController();abort.current=controller;setExtracting(true);setExtractError('');try {await data.mutate(()=>extractMaterial(selected.id,{signal:controller.signal,onProgress:refresh}));}catch(e){if(mounted.current)setExtractError(e instanceof Error?e.message:'Ekstraksi gagal.');}finally{abort.current=null;if(mounted.current){setExtracting(false);await refresh();}}}
 async function mutate(action:()=>Promise<unknown>){await data.mutate(action);await refresh();}
 return <><PageHeading eyebrow="教材チェック / MATERIAL REVIEW" title="Periksa sebelum dipelajari." description="Hanya teks PDF yang digunakan. Setiap draf memerlukan pemeriksaan dan persetujuan Anda." /><DataState><div className="material-check"><Card className="extraction-control"><label>PDF sumber<select aria-label="PDF sumber" value={materialId} disabled={extracting} onChange={e=>{setParams(e.target.value?{pdf:e.target.value}:{});setPageNumber('all');}}><option value="">Pilih PDF unggahan</option>{data.materials.filter(m=>m.file).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="entry-actions"><Button disabled={!selected||extracting} onClick={()=>void extract()}><ScanText size={17}/>{extracting?'Mengekstrak teks…':run?'Lanjutkan / periksa hasil':'Extract text'}</Button>{extracting&&<Button variant="secondary" onClick={()=>abort.current?.abort()}>Hentikan ekstraksi</Button>}{selected&&<Link className="button button-secondary" to={`/materials/${selected.id}`}>Read PDF</Link>}<Link className="text-link" to="/materials">Upload PDF</Link></div><ErrorMessage message={extractError||loadError}/>{loadError&&<Button onClick={()=>void refresh()}>Muat ulang draf</Button>}{run&&<><p role="status">{run.processedPages} / {run.totalPages} halaman diperiksa · {run.status}</p><ProgressBar value={run.processedPages} max={run.totalPages} label="Progres ekstraksi"/><p className="small-note">{run.textPages} halaman teks · {run.ocrPages} tanpa teks · {run.errorPages} gagal · {relevant.filter(d=>d.status==='PENDING').length} draf menunggu</p><ErrorMessage message={run.error}/>{!extracting&&run.status==='RUNNING'&&<p className="small-note">Proses sebelumnya mungkin terputus. Lanjutkan untuk memakai hasil halaman yang sudah tersimpan; proses aktif di tab lain tidak akan digandakan.</p>}</>}
 {run?.ocrPages? <div className="info-banner"><strong>Text extraction unavailable. OCR required.</strong><p>{run.ocrPages} halaman tidak menyediakan teks. Halaman gambar atau kosong tidak menghasilkan materi. Penyedia OCR dapat ditambahkan nanti.</p></div>:null}
 </Card><p className="small-note">Meaning dan terjemahan disalin dalam bahasa asli PDF, tanpa terjemahan otomatis. Kolom kosong berarti informasi belum ditemukan. Semua identifikasi otomatis berstatus Needs Review.</p>
 {!selected?<EmptyState icon={FileCheck2} title={materialId?'PDF tidak tersedia':'Pilih sumber belajarmu.'} description="Unggah atau pilih PDF untuk mengekstrak teks dan memeriksa calon materi." to="/materials" action="Buka koleksi PDF"/>:<>
 <div className="extraction-filters"><label>Status<select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDING">Needs Review</option><option value="APPROVED">Approved</option><option value="DELETED">Deleted</option></select></label><label>Jenis<select aria-label="Jenis" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Semua jenis</option><option value="vocabulary">Vocabulary</option><option value="grammar">Grammar</option><option value="example">Example sentences</option></select></label><label>Source page<select aria-label="Source page" value={pageNumber} onChange={e=>setPageNumber(e.target.value)}><option value="all">Semua halaman</option>{own.map(p=><option key={p.id} value={p.pageNumber}>Halaman {p.pageNumber}</option>)}</select></label></div>
 {!editing&&!approving&&!removing&&<ErrorMessage message={operation.error}/>}
 {!filtered.length&&<Card className="extraction-card"><p>{run?'Tidak ada draf pada filter ini. Teks dapat tersedia tanpa pola yang cukup jelas untuk diidentifikasi.':'Mulai Extract text untuk membuat draf dari PDF.'}</p></Card>}
 <div className="extraction-grid">{filtered.slice(index*12,index*12+12).map(d=><Card key={d.id} className="extraction-card"><div className="entry-actions"><Badge tone={d.status==='PENDING'?'orange':'neutral'}>{d.status==='PENDING'?'⚠️ Needs Review':d.status}</Badge><Badge tone="neutral">{d.kind}</Badge></div><h2>{d.fields.kanji||d.fields.pattern||d.fields.example}</h2><dl className="draft-fields">{fieldsFor(d.kind).filter(k=>!['romaji','partOfSpeech'].includes(k)).map(k=><div key={k}><dt>{labels[k]}</dt><dd lang={['kanji','kana','pattern','formation','example'].includes(k)?'ja':undefined}>{d.fields[k]||'Tidak ditemukan di PDF'}</dd></div>)}</dl><Link className="text-link" to={`/materials/${d.sourcePdfId}?page=${d.sourcePage}`}>Source page {d.sourcePage} · Buka PDF</Link><details><summary>Cuplikan sumber & alasan pemeriksaan</summary><pre className="source-excerpt">{d.sourceText}</pre>{d.reasons.map(reason=><p className="small-note" key={reason}>{reason}</p>)}</details>{d.status==='PENDING'?<><p className="small-note">{missingFields(d).length?`Lengkapi dari PDF: ${missingFields(d).join(', ')}.`:'Isi utama tersedia; periksa kecocokannya pada PDF.'} {d.kind!=='example'&&!d.jlptLevel?'Pilih level belajar melalui Edit.':''}</p><div className="entry-actions"><Button variant="secondary" disabled={operation.busy||extracting} onClick={()=>setEditing(d)}>Edit</Button><Button disabled={operation.busy||extracting} onClick={()=>setApproving(d)}>Approve</Button><Button variant="secondary" disabled={operation.busy||extracting} onClick={()=>setRemoving(d)}>Delete</Button></div></>:d.status==='APPROVED'&&<Link className="text-link" to={d.kind==='example'?`/${d.targetType}/${d.targetId}`:`/${d.kind}/${d.approvedItemId}`}>Buka materi disetujui</Link>}</Card>)}</div>
 {filtered.length>12&&<div className="entry-actions"><Button variant="secondary" disabled={index===0} onClick={()=>setPageIndex(index-1)}>Sebelumnya</Button><span>{index+1} / {maxPage+1} · {filtered.length} draf</span><Button variant="secondary" disabled={index===maxPage} onClick={()=>setPageIndex(index+1)}>Berikutnya</Button></div>}
 <Card className="extraction-card"><h2>Teks per halaman</h2><p className="small-note">Urutan teks PDF, kolom, dan furigana dapat ambigu. Cocokkan dengan tampilan PDF; teks ini tidak dijalankan sebagai instruksi.</p>{pageNumber==='all'&&own.length>20&&<p className="small-note">Menampilkan 20 halaman pertama. Gunakan filter Source page untuk membuka teks halaman lainnya.</p>}{(pageNumber==='all'?own.slice(0,20):own.filter(p=>p.pageNumber===Number(pageNumber))).map(p=><details key={p.id}><summary>Halaman {p.pageNumber} · {p.extractionStatus}</summary><Link className="text-link" to={`/materials/${materialId}?page=${p.pageNumber}`}>Buka halaman sumber</Link>{p.extractionStatus==='OCR_REQUIRED'?<p>Text extraction unavailable. OCR required.</p>:p.extractionStatus==='ERROR'?<ErrorMessage message={p.extractionError??'Halaman gagal.'}/>:<pre className="source-excerpt">{p.text}</pre>}</details>)}</Card>
 </>}
 </div></DataState>{editing&&<DraftEditor key={editing.id} draft={editing} pages={own} busy={operation.busy} error={operation.error} onClose={()=>setEditing(null)} onSave={changes=>void operation.run(()=>mutate(()=>database.extraction.edit(editing.id,editing.revision,changes)),()=>setEditing(null))}/>}
 {approving&&<Modal title="Approve materi" busy={operation.busy} onClose={()=>setApproving(null)}><p>Periksa isian dan halaman sumber sebelum memasukkan materi ini ke Learning Database.</p><p className="small-note">Informasi yang belum ada di PDF tidak boleh diisi dengan tebakan. Level belajar adalah pilihan pengelompokan pribadi. Kesulitan memakai nilai awal aplikasi 3/5, bukan hasil penilaian PDF.</p><Link className="text-link" to={`/materials/${approving.sourcePdfId}?page=${approving.sourcePage}`}>Buka halaman {approving.sourcePage}</Link><form className="data-form" onSubmit={e=>{e.preventDefault();const confirmed=new FormData(e.currentTarget).get('confirmed')==='on';void operation.run(()=>mutate(()=>database.extraction.approve(approving.id,approving.revision,confirmed)),()=>setApproving(null));}}><label className="extraction-confirm"><input type="checkbox" name="confirmed" required/>Saya sudah mencocokkan isi dan hubungan contoh dengan PDF.</label><ErrorMessage message={operation.error}/><Button type="submit" disabled={operation.busy}>Approve ke Learning Database</Button></form></Modal>}
 {removing&&<Modal title="Delete draf?" busy={operation.busy} onClose={()=>setRemoving(null)}><p>Draf ini ditandai Deleted dan tidak akan muncul kembali saat ekstraksi dilanjutkan. Berkas PDF tidak berubah.</p><ErrorMessage message={operation.error}/><div className="form-actions"><Button variant="secondary" disabled={operation.busy} onClick={()=>setRemoving(null)}>Batal</Button><Button disabled={operation.busy} onClick={()=>void operation.run(()=>mutate(()=>database.extraction.delete(removing.id,removing.revision)),()=>setRemoving(null))}>Delete draf</Button></div></Modal>}
 </>;
}
function DraftEditor({draft,pages,busy,error,onClose,onSave}:{draft:ExtractionDraft;pages:PDFPage[];busy:boolean;error:string;onClose:()=>void;onSave:(edit:DraftEdit)=>void}){
 const data=useData();const [kind,setKind]=useState(draft.kind),[fields,setFields]=useState(draft.fields),[targetType,setTargetType]=useState(draft.targetType);
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);onSave({kind,fields,jlptLevel:(form.get('level')||null) as JLPTLevel|null,targetType,targetId:String(form.get('target')??'')});}
 return <Modal title="Edit hasil extraction" busy={busy} onClose={onClose}><form className="data-form" onSubmit={save}><fieldset disabled={busy}><label>Jenis materi<select aria-label="Jenis materi" value={kind} onChange={e=>setKind(e.target.value as DraftKind)}><option value="vocabulary">Vocabulary</option><option value="grammar">Grammar</option><option value="example">Example sentence</option></select></label>{fieldsFor(kind).map(k=><label key={k}>{labels[k]}<textarea aria-label={labels[k]} value={fields[k]} onChange={e=>setFields({...fields,[k]:e.target.value})}/></label>)}{kind!=='example'?<label>Level belajar (pilihan Anda)<select aria-label="Level belajar (pilihan Anda)" name="level" defaultValue={draft.jlptLevel??''}><option value="">Pilih level</option>{['N5','N4','N3','N2'].map(l=><option key={l}>{l}</option>)}</select></label>:<><label>Jenis materi tujuan<select aria-label="Jenis materi tujuan" value={targetType} onChange={e=>setTargetType(e.target.value as ContentKind)}><option value="vocabulary">Vocabulary</option><option value="grammar">Grammar</option></select></label><label>Materi tujuan<select aria-label="Materi tujuan" name="target" defaultValue={draft.targetId}><option value="">Pilih materi yang cocok</option>{data[targetType].map(item=><option value={item.id} key={item.id}>{'kanji' in item?item.kanji:item.pattern} · {item.meaning}</option>)}</select></label></>}
 <p className="small-note">Salin hanya informasi yang benar-benar ada pada halaman {draft.sourcePage}. Biarkan kolom kosong bila tidak ditemukan; tidak ada transliterasi atau terjemahan otomatis.</p><details><summary>Teks halaman sumber</summary><pre className="source-excerpt">{pages.find(p=>p.pageNumber===draft.sourcePage)?.text}</pre></details></fieldset><ErrorMessage message={error}/><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Batal</Button><Button disabled={busy} type="submit">Simpan draf</Button></div></form></Modal>;
}
