import { useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { ListChecks } from 'lucide-react';
import { useData } from '../../app/data/DataProvider';
import { DataState, ErrorMessage, useOperation } from '../../components/DataState';
import { Badge, Button, Card, EmptyState, PageHeading } from '../../components/ui';
import type { JLPTLevel, QuizConfig } from '../../domain/models';
import { answerIsCorrect, questionAvailability, durationLabel, questionTypes } from '../../domain/quiz/engine';
import { database } from '../../services/database';
import { QuizFeedback } from './QuizFeedback';
import { QuizRunner } from './QuizRunner';
import { useQuizRecords } from './useQuizRecords';
const levels: JLPTLevel[] = ['N5','N4','N3','N2'];
export function QuizPage() {
 const [params] = useSearchParams();
 return params.has('attempt') ? <ActiveQuizPage /> : <QuizSetup />;
}
function ActiveQuizPage() {
 const records = useQuizRecords(); const [params] = useSearchParams();
 const attemptId = params.get('attempt'); const attempt = records.attempts.find(a => a.id === attemptId);
 const feedbackIndex = params.has('feedback') ? Number(params.get('feedback')) : -1;
 const feedback = attempt && Number.isInteger(feedbackIndex) && feedbackIndex === attempt.answers.length - 1 ? attempt.answers[feedbackIndex] : undefined;
 return <><PageHeading eyebrow="クイズ / LATIHAN" title="Satu soal, satu langkah." description="Jawaban disimpan saat kamu melanjutkan. Jawaban salah disertai pembahasan dan tautan materi terkait." />{records.loading ? <p role="status">Membuka sesi quiz…</p> : records.error ? <><ErrorMessage message={records.error} /><Button onClick={() => void records.reload()}>Coba lagi</Button></> : attempt && feedback && !answerIsCorrect(attempt.questions[feedbackIndex], feedback.answer) ? <Card className="quiz-runner"><h2 className="quiz-prompt">{attempt.questions[feedbackIndex].prompt}</h2><QuizFeedback question={attempt.questions[feedbackIndex]} answer={feedback.answer} /><Link className="button button-primary" to={attempt.status === 'COMPLETED' ? `/quiz/result?id=${attempt.id}` : `/quiz?attempt=${attempt.id}`}>{attempt.status === 'COMPLETED' ? 'Lihat hasil quiz' : 'Lanjut ke soal berikutnya'}</Link></Card> : attempt ? <QuizRunner key={`${attempt.id}:${attempt.answers.length}`} attempt={attempt} onSaved={records.reload} /> : <EmptyState icon={ListChecks} title="Sesi tidak ditemukan" description="Buka quiz baru atau pilih sesi dari riwayat." to="/quiz" action="Kembali ke quiz" />}</>;
}
function QuizSetup() {
 const data = useData(), records = useQuizRecords(); const navigate = useNavigate();
 const [mode, setMode] = useState<QuizConfig['mode']>('mixed'), [count, setCount] = useState<QuizConfig['count']>(10);
 const [chosenLevel, setLevel] = useState<string | null>(null);
 const availableLevels = levels.filter(l => [...data.vocabulary, ...data.grammar].some(item => item.jlptLevel === l));
 const level = chosenLevel ?? availableLevels[0] ?? 'N5';
 const [customLevels, setCustomLevels] = useState<JLPTLevel[]>(['N3','N2']);
 const [categoryIds, setCategoryIds] = useState<string[]>([]), [types, setTypes] = useState(questionTypes.map(q => q.value));
 const [historyPage, setHistoryPage] = useState(1); const { busy, error, run } = useOperation(); const lock = useRef(false);
 const selectedLevels = useMemo(() => level === 'Custom' ? customLevels : [level as JLPTLevel], [level,customLevels]);
 const selectedCategories = useMemo(() => level === 'Custom' ? categoryIds : [], [level,categoryIds]);
 const config: QuizConfig = useMemo(() => ({ mode, count, levels: selectedLevels, categoryIds: selectedCategories, types: level === 'Custom' ? types : questionTypes.map(q => q.value) }),[mode,count,level,selectedLevels,selectedCategories,types]);
 const selection = useMemo(() => {
  try { return { availability: config.levels.length ? questionAvailability(data, { ...config, count: 10, types: questionTypes.map(q=>q.value) }) : null, error: '' }; }
  catch (cause) { return { availability: null, error: cause instanceof Error ? cause.message : 'Pengaturan quiz tidak valid.' }; }
 }, [data.vocabulary, data.grammar, data.examples, config.mode, config.levels, config.categoryIds]);
 const countForType = (type: QuizConfig['types'][number]) => selection.availability?.byType[type] ?? 0;
 const vocabularyCount = questionTypes.filter(q => q.kind === 'vocabulary' && config.types.includes(q.value)).reduce((sum,q)=>sum+countForType(q.value),0);
 const grammarCount = questionTypes.filter(q => q.kind === 'grammar' && config.types.includes(q.value)).reduce((sum,q)=>sum+countForType(q.value),0);
 const available = mode === 'mixed' ? Math.min(vocabularyCount,grammarCount) * 2 : vocabularyCount + grammarCount;
 const active = records.attempts.filter(a => a.status === 'ACTIVE');
 return <><PageHeading eyebrow="クイズ / QUIZ" title="Uji pemahamanmu." description="Pilih materi, kerjakan soal, lalu pelajari setiap kesalahan." /><DataState><div className="quiz-setup-grid"><Card className="detail-content"><h2>Atur sesi belajar</h2><form className="data-form quiz-config" onSubmit={e => { e.preventDefault(); if(lock.current) return; lock.current = true; void run(async () => { const a = await database.quiz.start(config); await records.reload(); navigate(`/quiz?attempt=${a.id}`); }).finally(() => { lock.current = false; }); }}><fieldset disabled={busy}><ErrorMessage message={selection.error} /><div className="form-columns"><label>Materi quiz<select aria-label="Materi quiz" value={mode} onChange={e => setMode(e.target.value as QuizConfig['mode'])}><option value="vocabulary">Vocabulary</option><option value="grammar">Grammar</option><option value="mixed">Mixed</option></select></label><label>Jumlah soal<select aria-label="Jumlah soal" value={count} onChange={e => setCount(Number(e.target.value) as QuizConfig['count'])}>{[10,20,30,50].map(n => <option key={n} value={n}>{n}</option>)}</select></label></div><label>Level quiz<select aria-label="Level quiz" value={level} onChange={e => setLevel(e.target.value)}>{[...levels,'Custom'].map(l => <option key={l}>{l}</option>)}</select></label>
 {level === 'Custom' && <><fieldset className="category-checkboxes"><legend>Level yang disertakan</legend>{levels.map(l => <label key={l}><input type="checkbox" checked={customLevels.includes(l)} onChange={e => setCustomLevels(e.target.checked ? [...customLevels,l] : customLevels.filter(v => v !== l))} />{l}</label>)}</fieldset><fieldset className="category-checkboxes"><legend>Kategori · kosong berarti semua</legend>{data.categories.map(c => <label key={c.id}><input type="checkbox" checked={categoryIds.includes(c.id)} onChange={e => setCategoryIds(e.target.checked ? [...categoryIds,c.id] : categoryIds.filter(id => id !== c.id))} />{c.name}</label>)}</fieldset><fieldset className="category-checkboxes"><legend>Jenis soal</legend>{questionTypes.filter(q => mode === 'mixed' || q.kind === mode).map(q => <label key={q.value}><input type="checkbox" disabled={countForType(q.value) === 0} checked={types.includes(q.value) && countForType(q.value) > 0} onChange={e => setTypes(e.target.checked ? [...types,q.value] : types.filter(t => t !== q.value))} />{q.label} · {countForType(q.value)} soal{countForType(q.value) === 0 && " (belum tersedia)"}</label>)}</fieldset></>}
 {mode !== 'vocabulary' && <div className="info-banner" aria-live="polite"><p>Fill in blank grammar: {countForType('grammar-blank')} soal · Correct sentence: {countForType('grammar-sentence')} soal (sesuai level dan kategori).</p>{(!countForType('grammar-blank') || !countForType('grammar-sentence')) && <p>Materi belum mendukung sebagian jenis soal ini. Isi bagian “Soal grammar tervalidasi” saat mengedit grammar: kalimat, terjemahan, jawaban isian, dan pembahasan. Correct sentence juga memerlukan tiga kalimat pengecoh yang telah diperiksa. <Link to="/grammar">Lengkapi grammar</Link></p>}</div>}
 <p className="small-note" aria-live="polite">Tersedia: {vocabularyCount} soal Kotoba · {grammarCount} soal Bunpou. {mode === 'mixed' && 'Mixed memakai 50% vocabulary dan 50% grammar.'}</p>{available < count && <p className="info-banner" role="status">Soal belum cukup untuk {count} pertanyaan. Pilih jumlah lebih kecil atau perluas level, kategori, dan jenis soal. Tambahkan materi melalui impor JSON/CSV atau input manual. Pilihan ganda memerlukan minimal empat alternatif yang berbeda.</p>}<Button type="submit" disabled={busy || data.loading || !!data.error || available < count}>{busy ? 'Menyiapkan…' : 'Mulai quiz'}</Button></fieldset><ErrorMessage message={error} /></form></Card><Card className="detail-content"><h2>Berlatih dengan konteks</h2><p className="detail-paragraph">Urutan pertanyaan dan pilihan jawaban diacak setiap sesi. Isi bagian kosong dengan teks; soal lainnya memakai pilihan ganda.</p><p className="detail-paragraph">Soal mengikuti materi dan contoh yang tersedia. Satu materi bisa diuji melalui beberapa jenis soal, tanpa mengulang pertanyaan yang sama dalam satu sesi.</p><p className="info-banner">Quiz menggunakan vocabulary, grammar, dan contoh yang sudah kamu simpan. Hasil setiap sesi tersimpan di browser ini.</p><h3 className="detail-section-label">Jenis latihan</h3><div className="quiz-type-list">{questionTypes.map(q => <Badge key={q.value} tone="neutral">{q.label}</Badge>)}</div></Card></div></DataState>
 <section className="quiz-history"><h2>Lanjutkan sesi</h2><ErrorMessage message={records.error} />{records.error && <Button onClick={() => void records.reload()}>Muat ulang riwayat</Button>}{records.loading ? <p role="status">Membuka riwayat…</p> : !active.length ? <p className="muted">Tidak ada sesi yang belum selesai.</p> : active.map(a => <Card className="quiz-history-row" key={a.id}><div><strong>{a.config.mode} · {a.config.levels.join(', ')}</strong><p>{a.answers.length} / {a.questions.length} terjawab · {new Date(a.startedAt).toLocaleString('id-ID')}</p></div><Link className="button button-secondary" to={`/quiz?attempt=${a.id}`}>Lanjutkan</Link></Card>)}</section>
 <section className="quiz-history"><h2>Riwayat quiz</h2>{!records.loading && !records.results.length && <p className="muted">Hasil quiz pertamamu akan muncul di sini.</p>}{records.results.slice((historyPage-1)*10,historyPage*10).map(r => <Card className="quiz-history-row" key={r.id}><div><strong>{r.accuracy}% · {r.correctCount} / {r.answers.length}</strong><p>{r.config?.mode ?? 'Quiz'} · {new Date(r.finishedAt).toLocaleString('id-ID')} · {durationLabel(r.activeDurationSeconds)}</p></div><Link className="button button-secondary" to={`/quiz/result?id=${r.id}`}>Lihat hasil</Link></Card>)}{records.results.length > 10 && <div className="pagination"><Button variant="secondary" disabled={historyPage === 1} onClick={() => setHistoryPage(p => p-1)}>Sebelumnya</Button><span>{historyPage} / {Math.ceil(records.results.length/10)}</span><Button variant="secondary" disabled={historyPage*10 >= records.results.length} onClick={() => setHistoryPage(p => p+1)}>Berikutnya</Button></div>}</section></>;
}
