import { QuizFeedback } from './QuizFeedback';
import { Link, useSearchParams } from 'react-router-dom';
import { ListChecks } from 'lucide-react';
import { Badge, Button, Card, EmptyState, PageHeading } from '../../components/ui';
import { ErrorMessage } from '../../components/DataState';
import { answerText, categoryScore, durationLabel, questionTypes } from '../../domain/quiz/engine';
import { useQuizRecords } from './useQuizRecords';
export function QuizResultPage() {
 const [params] = useSearchParams(); const records = useQuizRecords();
 const result = params.has('id') ? records.results.find(r => r.id === params.get('id')) : records.results[0];
 const wrong = result?.answers.filter(a => !a.isCorrect) ?? [];
 return <><PageHeading eyebrow="結果 / HASIL QUIZ" title="Lihat kemajuanmu." description="Setiap kesalahan memberi arah untuk latihan berikutnya." /><Link className="text-link detail-back" to="/quiz">Kembali ke quiz & riwayat</Link>{records.loading ? <p role="status">Membuka hasil quiz…</p> : records.error ? <><ErrorMessage message={records.error} /><Button onClick={() => void records.reload()}>Coba lagi</Button></> : !result ? <EmptyState icon={ListChecks} title="Hasil quiz belum tersedia" description="Selesaikan sesi quiz untuk melihat skor dan pembahasannya." to="/quiz" action="Buka quiz" /> : <>
 <Card className="quiz-result-summary"><Badge>{result.config?.mode ?? 'Quiz'} · {result.config?.levels.join(', ') ?? 'Materi tersimpan'}</Badge><h2 className="quiz-score">{result.accuracy}%</h2><p className="small-note">Skor & akurasi</p><p className="quiz-score-count">{result.correctCount} / {result.answers.length}</p><p className="muted">jawaban benar · {result.wrongCount} salah · waktu aktif {durationLabel(result.activeDurationSeconds)}</p><div className="quiz-breakdown">{(['vocabulary','grammar'] as const).map(kind => <div key={kind}><span>{kind === 'vocabulary' ? 'Kotoba' : 'Bunpou'}</span><strong>{categoryScore(result,kind) === null ? 'Tidak diujikan' : `${categoryScore(result,kind)}%`}</strong></div>)}</div><p className="small-note">Selesai {new Date(result.finishedAt).toLocaleString('id-ID')}. Hasil tersimpan dan dapat dibuka kembali dari riwayat.</p></Card>
 <section className="quiz-history"><h2>Semua kesalahan ({wrong.length})</h2>{!wrong.length && <p className="info-banner">Tidak ada jawaban salah. Semua soal terjawab dengan benar.</p>}{wrong.map(row => { const q=row.questionSnapshot; return <Card className="quiz-mistake" key={q.id}><div className="entry-actions"><Badge tone="orange">Soal {result.answers.indexOf(row)+1} · {q.itemType === 'vocabulary' ? 'Kotoba' : 'Bunpou'}</Badge><Badge tone="neutral">{questionTypes.find(t => t.value === q.type)?.label ?? q.type}</Badge></div><h3 className="quiz-prompt">{q.prompt}</h3><QuizFeedback question={q} answer={row.answer} /></Card>; })}</section>
 <details className="quiz-all-answers"><summary>Lihat seluruh jawaban ({result.answers.length})</summary>{result.answers.map((row,i) => <Card className="quiz-answer-row" key={row.questionSnapshot.id}><Badge tone={row.isCorrect ? 'green' : 'orange'}>{i+1}. {row.isCorrect ? 'Benar' : 'Salah'}</Badge><p>{row.questionSnapshot.prompt}</p><p>Jawabanmu: {answerText(row.questionSnapshot,row.answer)}</p><p>Jawaban benar: {answerText(row.questionSnapshot,row.questionSnapshot.correctAnswer)}</p></Card>)}</details><p className="small-note">Skor mengukur jawaban dalam sesi ini. Hasil latihan pilihan ganda tidak membuktikan kelancaran berbahasa secara keseluruhan.</p></>}</>;
}
