import { useEffect,useRef,useState } from 'react';
import { Link,useNavigate,useSearchParams } from 'react-router-dom';
import { RotateCcw } from 'lucide-react';
import { useData } from '../../app/data/DataProvider';
import { Badge,Button,Card,EmptyState,PageHeading } from '../../components/ui';
import { DataState,ErrorMessage,useOperation } from '../../components/DataState';
import type { ReviewFilter } from '../../domain/models';
import { selectReviewQueue } from '../../domain/learning/review-queue';
import { effectiveReviewDate } from '../../domain/learning/spaced-repetition';
import { reviewDate } from '../../domain/learning/vocabulary';
import { database } from '../../services/database';
import { VocabularyProgress } from '../vocabulary/VocabularyProgress';
import { GrammarProgress } from '../grammar/GrammarProgress';
import { ReviewSession } from './ReviewSession';
import { useReviewRuns } from './useReviewRuns';
export function ReviewPage(){
 const data=useData(),records=useReviewRuns(),navigate=useNavigate();const [params,setParams]=useSearchParams();const [limit,setLimit]=useState(20),[now,setNow]=useState(Date.now());const {busy,error,run}=useOperation();const lock=useRef(false);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),10_000);return()=>clearInterval(t);},[]);
 const mode:ReviewFilter['mode']=params.get('type')==='grammar'?'grammar':params.get('type')==='mixed'?'mixed':'vocabulary';
 const level=params.get('level')??'all';const filter:ReviewFilter={mode,level:['N5','N4','N3','N2'].includes(level)?level as ReviewFilter['level']:'all',categoryId:params.get('category')??'',query:params.get('q')??''};
 const queue=selectReviewQueue(data.vocabulary,data.grammar,data.progress,filter,now);
 const allDue=selectReviewQueue(data.vocabulary,data.grammar,data.progress,{mode:'mixed'},now);
 const upcoming=data.progress.filter(p=>(mode==='mixed'||p.itemType===mode)&&!!(p.itemType==='vocabulary'?data.vocabulary:data.grammar).find(i=>i.id===p.itemId)&&!!effectiveReviewDate(p)&&Date.parse(effectiveReviewDate(p)!)>now).sort((a,b)=>effectiveReviewDate(a)!.localeCompare(effectiveReviewDate(b)!));
 const rawPage=Number(params.get('page')??1),pageCount=Math.max(1,Math.ceil(queue.length/12)),page=Math.min(pageCount,Math.max(1,Number.isInteger(rawPage)?rawPage:1));
 const setFilter=(key:string,value:string)=>{const next=new URLSearchParams(params);next.delete('page');if(value===''||value==='all')next.delete(key);else next.set(key,value);setParams(next,{replace:true,flushSync:true});};
 const sessionId=params.get('session'),selected=records.runs.find(r=>r.id===sessionId),back=`/review${params.toString()?`?${params}`:''}`;
 if(sessionId)return <><PageHeading eyebrow="復習 / SESI REVIEW" title="Ulangi, lalu beri jarak." description="Nilai ingatanmu setelah membandingkan jawaban. Setiap penilaian langsung disimpan." />{records.loading?<p role="status">Membuka sesi review…</p>:records.error?<><ErrorMessage message={records.error}/><Button onClick={()=>void records.reload()}>Coba lagi</Button></>:selected?<DataState><ReviewSession key={`${selected.id}:${selected.outcomes.length}`} session={selected} onSaved={records.reload}/></DataState>:<EmptyState icon={RotateCcw} title="Sesi review tidak ditemukan" description="Pilih materi yang jatuh tempo dari antrean." to="/review" action="Kembali ke review"/>}</>;
 return <><PageHeading eyebrow="復習 / REVIEW" title="Ingat lebih lama, sedikit setiap hari." description="Materi jatuh tempo diurutkan berdasarkan kesalahan, mastery, dan riwayat pengulangan."/><DataState><nav className="entry-actions detail-actions" aria-label="Jenis review">{(['vocabulary','grammar','mixed'] as const).map(type=><Link key={type} className={`button button-${mode===type?'primary':'secondary'}`} aria-current={mode===type?'page':undefined} to={type==='vocabulary'?'/review':`/review?type=${type}`}>{type==='vocabulary'?'Vocabulary':type==='grammar'?'Grammar':'Mixed'} <span>({allDue.filter(r=>type==='mixed'||r.progress.itemType===type).length})</span></Link>)}</nav>
 <div className="review-overview"><Card><strong>{queue.length}</strong><span>jatuh tempo sesuai filter</span></Card><Card><strong>{upcoming.length}</strong><span>terjadwal berikutnya · {mode}</span></Card><Card><strong>{upcoming[0]?reviewDate(effectiveReviewDate(upcoming[0])):'Belum ada'}</strong><span>jadwal terdekat · {mode}</span></Card></div>
 <p className="info-banner">Hanya materi yang sudah dijadwalkan atau pernah dilatih yang masuk antrean. Wrong mengulang lebih cepat; Good dan Easy memperpanjang interval. Membaca atau melewati kartu tidak menambah mastery.</p>
 <div className="content-toolbar"><label className="search-field"><input aria-label="Cari review" placeholder="Cari materi review…" value={filter.query} onChange={e=>setFilter('q',e.target.value)}/></label><label className="filter-field">Level<select aria-label="Filter level JLPT" value={filter.level} onChange={e=>setFilter('level',e.target.value)}><option value="all">Semua level</option>{['N5','N4','N3','N2'].map(l=><option key={l}>{l}</option>)}</select></label><label className="filter-field">Kategori<select aria-label="Filter kategori" value={filter.categoryId} onChange={e=>setFilter('category',e.target.value)}><option value="">Semua kategori</option>{data.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div>
 <div className="entry-actions review-start"><label className="filter-field">Batas sesi<select aria-label="Batas sesi review" value={limit} onChange={e=>setLimit(Number(e.target.value))}>{[10,20,50].map(n=><option value={n} key={n}>{n} materi</option>)}</select></label><Button disabled={busy||!queue.length} onClick={()=>{if(lock.current)return;lock.current=true;void run(async()=>{const session=await database.review.start(filter,limit);await records.reload();navigate(`/review?session=${session.id}`);}).finally(()=>{lock.current=false;});}}>Mulai review ({Math.min(limit,queue.length)})</Button>{mode==='vocabulary'&&queue.length>0&&<Link className="button button-secondary" to={`/vocabulary/flashcards?status=review&level=${filter.level}&category=${filter.categoryId||'all'}&q=${encodeURIComponent(filter.query??'')}`}>Flashcard</Link>}</div><ErrorMessage message={error}/>
 <p className="result-count muted">{queue.length} materi · Halaman {page} / {pageCount} · prioritas tertinggi di depan</p>{!queue.length?<EmptyState icon={RotateCcw} title="Tidak ada review yang jatuh tempo" description="Kembali saat jadwal berikutnya tiba, atau mulai belajar dari vocabulary, grammar, dan quiz." to="/vocabulary" action="Buka vocabulary"/>:<div className="content-grid">{queue.slice((page-1)*12,page*12).map(row=><Card className="content-card" key={row.progress.id}><div className="entry-actions"><Badge>{row.progress.itemType==='vocabulary'?'Kotoba':'Bunpou'}</Badge><Badge tone="neutral">{row.item.jlptLevel}</Badge></div><p className="entry-kanji grammar-pattern" lang="ja">{row.title}</p>{'kana'in row.item&&<p className="entry-reading" lang="ja">{row.item.kana}</p>}<h2>{row.item.meaning}</h2>{row.progress.itemType==='vocabulary'?<VocabularyProgress progress={{...row.progress,nextReview:row.nextReview}}/>:<GrammarProgress progress={{...row.progress,nextReview:row.nextReview}}/>}<p className="small-note">{row.progress.wrongCount} salah · {row.progress.correctCount} benar · {row.progress.reviewCount} review<br/>Terakhir: {reviewDate(row.progress.lastReviewed)}</p><div className="entry-actions"><Link className="button button-secondary" to={`/${row.progress.itemType}/${encodeURIComponent(row.item.id)}`} state={{backTo:back}}>Detail</Link></div></Card>)}</div>}
 {pageCount>1&&<div className="pagination"><Button variant="secondary" disabled={page===1} onClick={()=>setFilter('page',String(page-1))}>Sebelumnya</Button><span>{page} / {pageCount}</span><Button variant="secondary" disabled={page===pageCount} onClick={()=>setFilter('page',String(page+1))}>Berikutnya</Button></div>}
 <section className="quiz-history"><h2>Sesi review</h2><ErrorMessage message={records.error}/>{records.error&&<Button onClick={()=>void records.reload()}>Muat ulang sesi</Button>}{records.loading?<p role="status">Membuka sesi…</p>:records.runs.length===0?<p className="muted">Sesi tersimpan akan muncul di sini.</p>:[...records.runs.filter(s=>s.status==='ACTIVE'),...records.runs.filter(s=>s.status==='COMPLETED').slice(0,20)].map(s=><Card key={s.id} className="quiz-history-row"><div><strong>{s.filter.mode} · {s.status==='ACTIVE'?'Belum selesai':'Selesai'}</strong><p>{s.outcomes.filter(o=>o.rating!==null).length} dinilai · {s.outcomes.filter(o=>o.rating===null).length} dilewati · {s.entries.length} materi</p></div><Link className="button button-secondary" to={`/review?session=${s.id}`}>{s.status==='ACTIVE'?'Lanjutkan review':'Lihat ringkasan'}</Link></Card>)}</section></DataState></>;
}
