import { useEffect,useRef,useState } from 'react';
import { Link } from 'react-router-dom';
import type { FlashcardRating,QuizQuestion,ReviewRun,ReviewSchedule } from '../../domain/models';
import { progressKey } from '../../domain/models';
import { useData } from '../../app/data/DataProvider';
import { Badge,Button,Card,ProgressBar } from '../../components/ui';
import { ErrorMessage,useOperation } from '../../components/DataState';
import { intervalLabel,nextInterval,reviewGrades } from '../../domain/learning/spaced-repetition';
import { reviewDate } from '../../domain/learning/vocabulary';
import { database } from '../../services/database';
const prompts:Record<QuizQuestion['dimension'],{title:string;text:string}>={
 recognition:{title:'Pengenalan',text:'Tuliskan bacaan dan arti kata ini sebelum melihat jawaban.'},
 meaning:{title:'Makna',text:'Jelaskan arti kata ini dalam Bahasa Indonesia.'},
 kanji:{title:'Bacaan kanji',text:'Tuliskan bacaan kata ini menggunakan kana.'},
 usage:{title:'Penggunaan',text:'Jelaskan situasi yang tepat untuk memakai kata atau pola ini. Berikan contoh penggunaannya.'},
 understanding:{title:'Pemahaman',text:'Jelaskan arti pola ini serta cara pembentukannya dengan kata-katamu sendiri.'},
 sentence:{title:'Penyusunan kalimat',text:'Buat satu kalimat Jepang menggunakan pola ini dan tuliskan terjemahannya.'},
};
export function ReviewSession({session,onSaved}:{session:ReviewRun;onSaved:()=>Promise<void>}){
 const data=useData(),index=session.outcomes.length,entry=session.entries[index];const {busy,error,run}=useOperation();
 const [response,setResponse]=useState(''),[revealed,setRevealed]=useState(false),[schedule,setSchedule]=useState<ReviewSchedule>(),[loading,setLoading]=useState(true),[scheduleError,setScheduleError]=useState('');
 const lock=useRef(false),seconds=useRef(0),pending=useRef<{rating:FlashcardRating;response:string;seconds:number}|null>(null);
 useEffect(()=>{if(!entry)return;let live=true;void database.schedules.get(progressKey(entry.itemType,entry.itemId)).then(s=>{if(live){setSchedule(s);setLoading(false);}}).catch(e=>{if(live){setScheduleError(e instanceof Error?e.message:'Jadwal gagal dimuat.');setLoading(false);}});const timer=setInterval(()=>{if(!document.hidden&&!lock.current)seconds.current++;},1000);return()=>{live=false;clearInterval(timer);};},[entry?.itemId,entry?.itemType]);
 const back=session.filter.mode==='vocabulary'?'/review':`/review?type=${session.filter.mode}`;
 if(session.status==='COMPLETED')return <Card className="flashcard-complete"><Badge>Sesi review selesai</Badge><h2>{session.outcomes.some(o=>o.rating!==null)?'Jadwal berikutnya sudah tersimpan.':'Sesi selesai tanpa penilaian.'}</h2><p>{session.outcomes.filter(o=>o.rating!==null).length} materi dinilai · {session.outcomes.filter(o=>o.rating===null).length} dilewati</p><div className="rating-summary">{reviewGrades.map(g=><div key={g.value}><span>{g.label}</span><strong>{session.outcomes.filter(o=>o.rating===g.value).length}</strong></div>)}</div><p className="small-note">Mastery, jumlah benar/salah, jumlah review, dan tanggal review diperbarui untuk setiap penilaian. Materi yang dilewati tetap mengikuti jadwal sebelumnya.</p><div className="review-outcomes">{session.outcomes.map((o,i)=><div className="review-outcome" key={`${o.itemType}:${o.itemId}`}><div><strong>{i+1}. {o.title}</strong><p>{o.skippedReason??`${reviewGrades.find(g=>g.value===o.rating)?.label} · Mastery ${o.masteryScore}%`}</p></div><span>{o.rating===null?'Tidak dinilai':reviewDate(o.nextReview)}</span></div>)}</div><Link className="button button-primary" to={back}>Kembali ke antrean review</Link></Card>;
 const item=entry&&(entry.itemType==='vocabulary'?data.vocabulary:data.grammar).find(i=>i.id===entry.itemId);
 const progress=entry&&data.progress.find(p=>p.itemType===entry.itemType&&p.itemId===entry.itemId);
 if(!entry)return <p role="alert">Urutan sesi tidak valid.</p>;
 const examples=data.examples.filter(e=>e.itemType===entry.itemType&&e.itemId===entry.itemId);
 function rate(rating:FlashcardRating){if(lock.current||!revealed)return;lock.current=true;pending.current??={rating,response,seconds:seconds.current};const input=pending.current;void run(async()=>{await data.mutate(()=>database.review.answer(session.id,index,input.rating,input.response,input.seconds));await onSaved();}).finally(()=>{lock.current=false;});}
 return <Card className="quiz-runner"><div className="quiz-session-meta"><Badge>{entry.itemType==='vocabulary'?'Kotoba':'Bunpou'} · {prompts[entry.dimension].title}</Badge><span aria-live="polite">Materi {index+1} / {session.entries.length}</span></div><ProgressBar value={index} max={session.entries.length} label="Kemajuan review"/>{!item||!progress?<p className="info-banner">Materi atau progres ini sudah dihapus. Lewati untuk melanjutkan sesi.</p>:<><h2 className="review-word" lang="ja">{'kanji'in item?item.kanji:item.pattern}</h2><p className="detail-paragraph">{prompts[entry.dimension].text}</p><form className="data-form" onSubmit={e=>{e.preventDefault();setRevealed(true);}}><label>Jawaban review<textarea aria-label="Jawaban review" value={response} maxLength={4000} disabled={revealed||busy||!!pending.current} onChange={e=>setResponse(e.target.value)}/></label>{!revealed&&<Button disabled={busy} type="submit">Lihat jawaban</Button>}</form>
 {revealed&&<section className="review-answer"><Badge tone="neutral">Bandingkan dengan materi</Badge><h3>{item.meaning}</h3>{'kana'in item?<p lang="ja">{item.kana} · {item.romaji} · {item.partOfSpeech}</p>:<><p className="grammar-form" lang="ja">{item.formation}</p><p className="detail-paragraph">{item.explanation}</p>{item.commonMistakes&&<p className="detail-paragraph">{item.commonMistakes}</p>}</>}{examples.map(e=><blockquote className="example-block" key={e.id}><p lang="ja">{e.japanese}</p><p>{e.translation}</p></blockquote>)}<Button variant="secondary" disabled={busy||!!pending.current} onClick={()=>setRevealed(false)}>Perbaiki jawaban</Button></section>}
 <p className="small-note review-rating-note">Penilaian diri: Wrong = salah/belum ingat; Hard = benar dengan susah payah; Good/Easy = benar. Jika belum menulis jawaban, hanya Wrong yang dapat dipilih. Aspek dengan bukti paling lemah dilatih lebih dahulu.</p><div className="rating-buttons">{reviewGrades.map(g=><Button key={g.value} variant="secondary" disabled={!revealed||busy||loading||!!scheduleError||(g.value>0&&!response.trim())||(!!pending.current&&pending.current.rating!==g.value)} onClick={()=>rate(g.value)}><span>{g.label}</span><small>{loading?'Memuat jadwal…':intervalLabel(nextInterval(schedule,g.value))}</small></Button>)}</div></>}
 <ErrorMessage message={error||scheduleError}/>{scheduleError&&<Button onClick={()=>window.location.reload()}>Muat ulang sesi</Button>}<div className="flashcard-footer"><Link className="text-link" to={back}>Keluar sementara</Link><Button variant="secondary" disabled={busy||!!pending.current} onClick={()=>{if(lock.current)return;lock.current=true;void run(async()=>{await database.review.skip(session.id,index);await onSaved();}).finally(()=>{lock.current=false;});}}>Lewati tanpa menilai</Button></div><p className="small-note">Jawaban yang dinilai tersimpan setelah konfirmasi. Sesi dapat dilanjutkan setelah refresh; teks yang belum dikirim belum tersimpan.</p></Card>;
}
